### PR TITLE
Reject empty password

### PR DESCRIPTION
**Pull request by signedav**
It's regarding this issue here https://github.com/3liz/lizmap-web-client/issues/1057

I make this pull request because I used this on our customer solution. But I don't blame you for rejecting it, if you don't like it.

If you have inputs, how to make it better or why it's not good, then I'm happy to hear them anyway. Thanks.

### CODE REVIEW

**Comment by laurentj** [comment]
I'm ok to disallow empty password. But I think the default behavior must be to forbid empty password, and having an option to allow empty password. In fact, I'm not sure there should be a such option. It does not make sens, right?

**Comment by signedav** [comment]
I do agree. I made this as an option, because I did not want to change the default behavior we have at the moment (because I do not understand the whole concept). But if you think so, I do agree. Should I remove the option and commit again or do you want to care for it?

**Comment by laurentj** [comment]
Here is my commit : 9ce9860a58611d681d7f46b6fab04a3c5c87388c

Thank you for your report

**Comment by signedav** [comment]
Thanks  @laurentj

**Pull request closed without merging**
